name: 'Setup Dotnet environment'
description: 'Setup a Dotnet environment and add it to the PATH, additionally providing proxy support'
author: 'GitHub'
inputs: 
  dotnet-version:
    description: 'SDK version to use. E.g. 2.2.104'
# Deprecated option, do not use. Will not be supported after October 1, 2019
  version:
    description: 'Deprecated. Use dotnet-version instead. Will not be supported after October 1, 2019'
    deprecationMessage: 'The version property will not be supported after October 1, 2019. Use dotnet-version instead'
runs:
  using: 'node12'
  main: 'lib/setup-dotnet.js'
